import {
  Home,
  User,
  Settings,
  FileText,
  LogIn,
  UserPlus,
  Users,
  Bell,
  Key,
  CheckSquare,
  FileImage,
} from "lucide-react";

export const groupedItems = [
  {
    group: "Inicio",
    items: [
      {
        name: "Inicio",
        link: "/inicio",
        icon: Home,
        tags: [
          "dashboard",
          "principal",
          "home",
          "página principal",
          "pagina principal",
          "inicio",
          "bienvenida",
          "pantalla inicial",
          "start",
          "bienvenida",
          "inicio rápido",
          "inicio sesión",
          "vista principal",
          "pantalla de inicio",
          "acceso principal",
          "inicio principal",
        ],
      },
      {
        name: "Landing Page",
        link: "/home",
        icon: Home,
        tags: [
          "bienvenida",
          "portada",
          "landing",
          "página de inicio",
          "pagina de inicio",
          "inicio",
          "bienvenida",
          "entrar",
          "acceso inicial",
          "home page",
          "pagina de aterrizaje",
          "web landing",
          "inicio rápido",
          "acceso a la plataforma",
          "inicio de plataforma",
          "bienvenida inicial",
        ],
      },
    ],
  },
  {
    group: "Configuración",
    items: [
      {
        name: "Perfil",
        link: "/configuracion/perfil",
        icon: User,
        tags: [
          "usuario",
          "datos",
          "información personal",
          "mi cuenta",
          "mi perfil",
          "foto de perfil",
          "datos personales",
          "ajustes personales",
          "cuenta",
          "información del usuario",
          "editar perfil",
          "configuración personal",
          "editar información",
          "ajustes de cuenta",
          "gestionar perfil",
        ],
      },
      {
        name: "Cuenta",
        link: "/configuracion/cuenta",
        icon: Settings,
        tags: [
          "contraseña",
          "preferencias",
          "configuración",
          "configuracion",
          "settings",
          "opciones",
          "ajustes de cuenta",
          "seguridad",
          "actualizar",
          "gestión de cuenta",
          "ajustes de seguridad",
          "cambiar contraseña",
          "opciones de cuenta",
          "ajustes avanzados",
          "configuración de seguridad",
        ],
      },
      {
        name: "Seguridad",
        link: "/configuracion/sesiones",
        icon: Settings,
        tags: [
          "contraseña",
          "seguridad",
          "sesiones",
          "configuración",
          "configuracion",
          "login",
          "seguridad de cuenta",
          "logout",
          "cierre de sesión",
          "gestionar sesiones",
          "control de sesiones",
          "autenticación",
          "cambio de contraseña",
          "ver sesiones",
          "cerrar sesión",
          "bloquear cuenta",
        ],
      },
      {
        name: "Mis notificaciones",
        link: "/notificaciones",
        icon: Bell,
        tags: [
          "ajustes",
          "preferencias",
          "configuración",
          "notificaciones",
          "alertas",
          "avisos",
          "mensajes",
          "notificaciones push",
          "alertas",
          "notificaciones por correo",
          "avisos importantes",
          "alertas personalizadas",
          "opciones de notificación",
          "gestionar notificaciones",
          "tendencias de notificación",
        ],
      },
    ],
  },
  {
    group: "Pagos",
    items: [
      {
        name: "Mis Pagos",
        link: "/pagos",
        icon: FileText,
        tags: [
          "transacciones",
          "facturación",
          "facturacion",
          "pagos",
          "cobros",
          "dinero",
          "recibos",
          "historial de pagos",
          "facturas",
          "pagos pendientes",
          "historial de transacciones",
          "reporte de pagos",
          "balance de pagos",
          "estado de cuenta",
          "facturación mensual",
          "gestión de pagos",
          "transacciones realizadas",
        ],
        badge: "Nuevo",
      },
      {
        name: "Comprobantes de pago del congreso",
        link: "/comprobantes/lista",
        icon: FileText,
        tags: [
          "facturas",
          "recibos",
          "comprobantes",
          "boletas",
          "vouchers",
          "documentos de pago",
          "congreso",
          "cobros",
          "validar pagos",
          "recibos electrónicos",
          "documentación fiscal",
          "comprobantes legales",
          "pagos confirmados",
          "facturas de congresos",
          "pagos congresuales",
          "ver comprobantes",
        ],
      },
      {
        name: "Comprobantes de pago del evento académico",
        link: "/comprobantesEventosAcademicos/lista",
        icon: FileText,
        tags: [
          "facturas",
          "recibos",
          "comprobantes",
          "boletas",
          "eventos académicos",
          "pago de eventos",
          "comprobantes",
          "vouchers",
          "certificación de pago",
          "documentación",
          "boletas académicas",
          "recibo académico",
          "comprobantes fiscales",
          "facturas de evento",
          "eventos pagados",
          "pago de seminarios",
        ],
      },
    ],
  },
  {
    group: "Autenticación",
    items: [
      {
        name: "Iniciar Sesión",
        link: "/login",
        icon: LogIn,
        tags: [
          "acceso",
          "login",
          "entrar",
          "ingresar",
          "acceder",
          "iniciar sesión",
          "inicio de sesión",
          "acceso a la cuenta",
          "conectar",
          "entrar a plataforma",
          "iniciar sesión en cuenta",
          "login de usuario",
          "inicio de sesión seguro",
          "acceso rápido",
          "plataforma de login",
          "autenticación de cuenta",
          "conexión",
          "acceso al sistema",
          "login usuario",
          "iniciar sesión rápido",
          "iniciar sesión seguro",
          "autenticación",
          "ingreso a plataforma",
          "inicio de sesión online",
          "acceso al portal",
          "login rápido",
        ],
      },
      {
        name: "Registrarme",
        link: "/registrar",
        icon: UserPlus,
        tags: [
          "crear cuenta",
          "signup",
          "registro",
          "nueva cuenta",
          "registrarse",
          "sign up",
          "crear usuario",
          "nuevo usuario",
          "registro en línea",
          "registro rápido",
          "crear perfil",
          "suscripción",
          "acceso nuevo",
          "inscripción",
          "registrarse ahora",
          "alta de usuario",
          "registro de cuenta",
          "alta de usuario nuevo",
          "nueva cuenta de usuario",
          "alta de cuenta",
          "registro de usuario",
          "crear cuenta nueva",
          "usuario registrado",
          "registro online",
          "completar formulario",
          "registro de acceso",
          "formulario de registro",
        ],
      },
      {
        name: "Olvidé mi contraseña",
        link: "/recuperar-password",
        icon: UserPlus,
        tags: [
          "recuperar contraseña",
          "olvidé contraseña",
          "restablecer contraseña",
          "recuperación de cuenta",
          "cambiar contraseña",
          "restaurar contraseña",
          "recuperar acceso",
          "restaurar cuenta",
          "cambiar mi clave",
          "recuperar mi cuenta",
          "restablecer mi contraseña",
          "cambio de contraseña",
          "olvide mi clave",
          "olvidé mi clave",
          "cambiar acceso",
          "cambiar clave de usuario",
          "restablecer acceso",
          "recuperación de seguridad",
          "seguridad de cuenta",
          "restaurar acceso",
          "gestionar contraseña",
          "cambio de credenciales",
        ],
      },
      {
        name: "Validar mi correo",
        link: "/validate-email",
        icon: UserPlus,
        tags: [
          "validar correo",
          "verificar email",
          "confirmar correo",
          "validación de correo",
          "confirmar email",
          "activar cuenta",
          "verificación de correo electrónico",
          "confirmar dirección de correo",
          "enviar validación de correo",
          "correo de confirmación",
          "verificación de cuenta",
          "activación de correo",
          "email de confirmación",
          "validar email",
          "verificar mi cuenta",
          "confirmación de cuenta",
          "verificar correo electrónico",
          "activación por correo",
          "confirmación de email",
          "validar dirección de email",
          "verificación de cuenta por correo",
          "enviar validación de cuenta",
        ],
      },
    ],
  },
  {
    group: "Congresos",
    items: [
      {
        name: "Gestión de Congresos",
        link: "/gestion-congresos",
        icon: Settings,
        tags: [
          "administrar",
          "eventos",
          "congresos",
          "gestionar",
          "administración",
          "organización",
          "eventos académicos",
          "congreso",
          "gestión de eventos",
          "eventos profesionales",
          "gestión de congresos",
          "coordinación de eventos",
          "planificar congresos",
          "eventos científicos",
          "administración de congresos",
          "gestión profesional",
        ],
      },
      {
        name: "Participar en Congresos",
        link: "/participar/congresos",
        icon: Users,
        tags: [
          "inscripción",
          "inscripcion",
          "asistir",
          "participar",
          "registrarse",
          "unirse",
          "evento académico",
          "congresistas",
          "participación",
          "congreso internacional",
          "registro de congresos",
          "asistir a eventos",
          "inscribirse",
          "formulario de participación",
          "congreso en línea",
          "eventos académicos",
        ],
      },
      {
        name: "Añadir asistencias en Congresos",
        link: "/activacion",
        icon: Users,
        tags: [
          "inscripción",
          "inscripcion",
          "asistir",
          "participar",
          "registrarse",
          "unirse",
          "añadir participantes",
          "confirmar asistencia",
          "asistencia a evento",
          "evento registrado",
          "participación confirmada",
          "gestionar participantes",
          "gestión de asistentes",
          "inscripción en masa",
          "evento de inscripción",
        ],
      },
    ],
  },
  {
    group: "Eventos",
    items: [
      {
        name: "Gestión de eventos",
        link: "/eventos/lista/congresos",
        icon: Settings,
        tags: [
          "calendario",
          "programación",
          "eventos",
          "agenda",
          "organizar",
          "eventos programados",
          "organización",
          "calendarizar",
          "eventos académicos",
          "planificación",
          "organización de eventos",
          "agenda de actividades",
          "eventos próximos",
          "eventos futuros",
          "reuniones programadas",
          "calendario de actividades",
        ],
      },
      {
        name: "Gestión de eventos académicos",
        link: "/eventos-academicos",
        icon: Settings,
        tags: [
          "calendario",
          "programación",
          "eventos académicos",
          "agenda",
          "organizar",
          "eventos académicos",
          "gestión de eventos",
          "planificar",
          "cursos",
          "seminarios",
          "agenda académica",
          "gestión de conferencias",
          "eventos educativos",
          "seminarios académicos",
          "evento académico",
        ],
      },
      {
        name: "Añadir asistencias en evento académico",
        link: "/activacion-academico",
        icon: Users,
        tags: [
          "inscripción",
          "inscripcion",
          "asistir",
          "participar",
          "registrarse",
          "unirse",
          "evento académico",
          "congresistas",
          "añadir participantes",
          "confirmar asistencia",
          "asistencia académica",
          "registro académico",
          "evento educativo",
          "asistencia en curso",
          "registrar asistencia",
        ],
      },
    ],
  },
  {
    group: "Certificados",
    items: [
      {
        name: "Ver mis Certificados",
        link: "/certificados",
        icon: FileImage,
        tags: [
          "plantillas",
          "templates",
          "diseño",
          "diseno",
          "personalizar",
          "editar",
          "modificar",
          "diseñar",
          "customizar",
          "crear certificados",
          "diseño gráfico",
          "crear diploma",
          "plantillas personalizadas",
          "personalizar certificado",
          "editar certificado",
          "diseño de documentos",
          "diseño de diploma",
          "certificados emitidos",
          "certificados disponibles",
          "consultar certificados",
          "documentos académicos",
          "ver certificados",
        ],
        badge: "Popular",
      },
      {
        name: "Buscar / Validar Certificados",
        link: "/certificados-emitidos",
        icon: FileImage,
        tags: [
          "validar",
          "buscar",
          "verificar",
          "certificados",
          "comprobar",
          "consultar",
          "confirmar",
          "acreditación",
          "certificados emitidos",
          "validar diploma",
          "buscar certificados",
          "verificar certificados",
          "buscar en lista",
          "revisión de certificados",
          "documentos validados",
          "validación de diploma",
          "certificación oficial",
          "verificación de documentos",
        ],
        badge: "Popular",
      },
      {
        name: "Diseñar Certificados",
        link: "/design-certificados/lista",
        icon: FileImage,
        tags: [
          "diseño",
          "plantillas",
          "templates",
          "personalizar",
          "editar",
          "modificar",
          "crear certificado",
          "diplomas",
          "diseño gráfico",
          "crear diploma",
          "personalizar plantilla",
          "editar documento",
          "diseño de certificados",
          "diseño profesional",
          "certificados personalizados",
          "plantillas personalizadas",
          "crear plantillas",
          "personalización de diploma",
        ],
        badge: "Nuevo",
      },
      {
        name: "Emitir Certificados congresos",
        link: "/generate-certificados/congresos",
        icon: CheckSquare,
        tags: [
          "crear",
          "diplomas",
          "certificados",
          "generar",
          "emitir",
          "hacer",
          "certificados congresos",
          "validación",
          "certificación",
          "emitir diplomas",
          "crear diploma",
          "acreditación",
          "entregar certificados",
          "certificados profesionales",
          "validar certificados",
          "emitir documento",
          "congreso",
          "certificados de evento",
          "generación de certificados",
          "certificados académicos",
        ],
      },
      {
        name: "Emitir Certificados eventos académicos",
        link: "/generate-certificados/eventos-academicos",
        icon: CheckSquare,
        tags: [
          "enviar",
          "publicar",
          "emitir",
          "certificados",
          "diplomas",
          "entregar",
          "acreditación",
          "validar",
          "enviar certificado",
          "entregar diploma",
          "gestión de certificados",
          "emitir documento",
          "acreditaciones",
          "certificación profesional",
          "validación de documentos",
          "certificados académicos",
          "generar diplomas",
          "gestión de certificados académicos",
          "emitir eventos",
        ],
      },
      {
        name: "Ver Certificados de congresos",
        link: "/certificados-emitidos/congreso",
        icon: CheckSquare,
        tags: [
          "listado",
          "historial",
          "certificados",
          "diplomas",
          "emitidos",
          "generados",
          "documentos emitidos",
          "certificados académicos",
          "recibir certificados",
          "certificados generados",
          "ver certificados",
          "historial de diplomas",
          "certificados conferencias",
          "acreditación",
          "ver emitidos",
          "certificados recibidos",
          "certificados conferencias",
          "historial de congresos",
          "consultar historial",
        ],
      },
      {
        name: "Ver Certificados de evento",
        link: "/certificados-emitidos/evento-academico",
        icon: CheckSquare,
        tags: [
          "listado",
          "historial",
          "certificados",
          "diplomas",
          "emitidos",
          "generados",
          "documentos emitidos",
          "certificados académicos",
          "recibir certificados",
          "certificados generados",
          "ver certificados",
          "historial de diplomas",
          "certificados conferencias",
          "acreditación",
          "ver emitidos",
          "certificados recibidos",
          "verificación de certificados",
          "eventos académicos",
          "certificados educativos",
        ],
      },
    ],
  },
  {
    group: "Administración",
    items: [
      {
        name: "Gestión de Usuarios",
        link: "/usuarios/lista",
        icon: Users,
        tags: [
          "miembros",
          "cuentas",
          "usuarios",
          "gestionar",
          "administrar",
          "personas",
          "usuarios registrados",
          "perfil de usuario",
          "gestión de cuentas",
          "gestión de usuarios",
          "gestión de acceso",
          "agregar usuarios",
          "editar perfiles",
          "administrar roles",
          "usuario registrado",
          "gestión de permisos",
        ],
      },
      {
        name: "Gestión de Participantes",
        link: "/tipo-participantes",
        icon: Users,
        tags: [
          "miembros",
          "cuentas",
          "usuarios",
          "gestionar",
          "administrar",
          "personas",
          "participantes",
          "tipos de participantes",
          "agregar participantes",
          "gestión de tipos",
          "gestión de registros",
          "gestión de asistencia",
          "inscripción de participantes",
          "gestionar acceso",
          "editar participantes",
        ],
      },
      {
        name: "Roles y permisos",
        link: "/roles/assign",
        icon: Key,
        tags: [
          "accesos",
          "seguridad",
          "permisos",
          "roles",
          "privilegios",
          "autorizaciones",
          "control de acceso",
          "administrar privilegios",
          "asignar permisos",
          "gestión de roles",
          "acceso de usuarios",
          "permisos de acceso",
          "autorización de roles",
          "administración de privilegios",
          "roles de seguridad",
          "permisos de administrador",
        ],
      },
      {
        name: "Emitir Notificaciones",
        link: "/notificaciones/emitir",
        icon: Bell,
        tags: [
          "alertas",
          "mensajes",
          "avisos",
          "notificaciones",
          "comunicados",
          "anuncios",
          "informar",
          "avisar",
          "alertas importantes",
          "notificaciones de sistema",
          "alertas de usuario",
          "enviar mensajes",
          "notificaciones urgentes",
          "alertas por correo",
          "enviar notificaciones",
          "comunicaciones importantes",
        ],
      },
      {
        name: "Ver Notificaciones emitidas",
        link: "/notificaciones/lista",
        icon: Bell,
        tags: [
          "alertas",
          "mensajes",
          "avisos",
          "notificaciones",
          "comunicados",
          "anuncios",
          "historial de notificaciones",
          "notificaciones enviadas",
          "mensajes previos",
          "registro de notificaciones",
          "ver notificaciones",
          "consultar notificaciones",
          "historial de avisos",
          "comunicados enviados",
        ],
      },
    ],
  },
];
